name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    if: ${{contains(github.event.head_commit.message, '[CI run]')}}

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
     
    - name: check node version 
      run: node -v

    - name: install dependences
      run: npm install

    - name: Run start script with timeout
      run: |
        npm run build & PID=$!
        (sleep 1200; kill $PID 2>/dev/null) &
        wait $PID
      timeout-minutes: 20
      continue-on-error: true
    - name: Check start script result
      run: |
        if [ $? -ne 0 ]; then
          echo "::warning::npm start command failed or timed out after 20 minutes"
        fi
